name: sensogrip_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_blue: ^0.8.0
  mp_chart: ^0.3.1
  flutter_colorpicker: ^0.5.0
  path_provider: ^1.6.28
  sqflite: ^2.0.0+2
  path: ^1.8.0
  intl: ^0.17.0
  provider: ^5.0.0
  wakelock: ^0.5.2
  camera: ^0.8.1
  screen_recorder_flutter: ^0.0.1
  flutter_pdfview: ^1.1.0
  http: ^0.13.2
  device_info: ^2.0.0
  connectivity: ^3.0.4
  native_device_orientation: ^1.0.0
  introduction_screen: ^2.1.0
  shared_preferences: ^0.5.12+4


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  #android: true
  #ios: true
  android: "launcher_icon"
  image_path: "dev_assets/icon.png"
  #adaptive_icon_background: "#191919"
  #adaptive_icon_foreground: "dev_assets/..."


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  #   - images/a_dot_burr.jpeg
    - assets/images/fhcampus_banner.png
    - assets/images/no_data.jpg
    - assets/images/add_user.png
    - assets/pdf/manual.pdf
    - assets/images/cloud.png
    - assets/images/analyze.png
    - assets/images/users.png
    - assets/images/feedback.png
    - assets/images/analyzeData.png
    - assets/images/profiles.png
    - assets/images/ledFeedback.png
    - assets/images/locked.png
    - assets/images/locked2.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: OpenSans
    fonts:
      - asset: assets/fonts/OpenSans-Regular.ttf
      - asset: assets/fonts/OpenSans-Bold.ttf
        weight: 700
  - family: Quicksand
    fonts:
      - asset: assets/fonts/Quicksand-Regular.ttf
      - asset: assets/fonts/Quicksand-Bold.ttf
        weight: 700
      - asset: assets/fonts/Quicksand-Light.ttf
      - asset: assets/fonts/Quicksand-Medium.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
