name: sensogrip_app
description: A Sensogrip Pencil companion App.
publish_to: 'none'
version: 2.0.2+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_blue: ^0.8.0
  mp_chart: ^0.3.1
  flutter_colorpicker: ^0.5.0
  path_provider: ^1.6.28
  sqflite: ^2.0.0+2
  path: ^1.8.0
  intl: ^0.17.0
  provider: ^5.0.0
  wakelock: ^0.5.2
  camera: ^0.8.1
  screen_recorder_flutter: ^0.0.1
  flutter_pdfview: ^1.1.0
  http: ^0.13.2
  device_info: ^2.0.0
  connectivity: ^3.0.4
  native_device_orientation: ^1.0.0
  introduction_screen: ^2.1.0
  shared_preferences: ^0.5.12+4
  cupertino_icons: ^1.0.2
  get: ^4.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  #android: true
  #ios: true
  android: "launcher_icon"
  image_path: "dev_assets/icon.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/fhcampus_banner.png
    - assets/images/no_data.jpg
    - assets/images/add_user.png
    - assets/pdf/manual.pdf
    - assets/images/cloud.png
    - assets/images/analyze.png
    - assets/images/users.png
    - assets/images/feedback.png
    - assets/images/analyzeData.png
    - assets/images/profiles.png
    - assets/images/ledFeedback.png
    - assets/images/locked.png
    - assets/images/locked2.png

  fonts:
  - family: OpenSans
    fonts:
      - asset: assets/fonts/OpenSans-Regular.ttf
      - asset: assets/fonts/OpenSans-Bold.ttf
        weight: 700
  - family: Quicksand
    fonts:
      - asset: assets/fonts/Quicksand-Regular.ttf
      - asset: assets/fonts/Quicksand-Bold.ttf
        weight: 700
      - asset: assets/fonts/Quicksand-Light.ttf
      - asset: assets/fonts/Quicksand-Medium.ttf
